### ISSUE TITLE
Compile error with ATTiny85 @ 8Mhz w/Optiboot

### ISSUE THREAD

**Issue by brisma** [leomil72/tiny#1]
Hi Leonardo,
there is a problem compiling for ATtiny85 @ 8Mhz w/Optiboot:

```
Opzioni di compilazione cambiate, ricompilo tutto
open /Users/brisma/Library/Arduino15/packages/tiny/hardware/avr/1.0.0/variants/tinyX5: no such file or directory
Errore durante la compilazione per la scheda ATtiny25/45/85.
```

The variants folder is missing:

<img width="835" alt="schermata 2016-05-30 alle 16 34 26" src="https://cloud.githubusercontent.com/assets/3034623/15652148/6a479e5e-2684-11e6-9760-227eae4d8c5f.png">

**Comment by leomil72** [comment]
When I created the core, some time ago, I made a mix using several pieces of different projects. Things worked well since the appearing of IDE 1.6, that changed the way the cores are made and integrated into the IDE itself. When I prepared the package for the new system based on the board manager I didn’t included some pieces. But they are the point of the iceberg. I didn’t try the Optiboot bootloader for the Tiny85 so I didn’t include it into the pakcage but I forgot to remove the entry from the menu. Yesterday I put the binary of the bootloader into the core but I realized that some files are still missing. And I don’t know if it really works or not. The cores that use a bootloader are slighty modified because Tiny85 doesn’t have an hardware serial nor a system division of the memory to preverse the overwriting of the flash occupied by the bootloader code. I will study the thing and will try to find a good solution, at the moment I will release as soon as possible the 1.0.2 version of the core with everything fixed for at least compile sketches and upload them but with no guarantee that the bootloader system will work correctly.

Ciao.
Leonardo Miliani
Web: www.leonardomiliani.com

**Comment by leomil72** [comment]
Released v. 1.0.3, general fixes for some bugs. If you still experience problems after upgrading, please uninstall and reinstall the core because I've done at least a couple of releases with the same revision number (1.0.3) so it could be possible that someone had installed a still-buggy version while I was doing some compiling tests. I apologize for his...
